In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer # Term frequency inverse document vectorizer
from sklearn.metrics.pairwise import linear_kernel 

In [2]:
movie_df = pd.read_csv('Movies_dataset.csv')

In [3]:
movie_df

Movie Title  Ratinng                     genre  \
0             3 Idiots      8.4             Comedy, Drama   
1     Taare Zameen Par      8.3             Drama, Family   
2                   PK      8.1     Comedy, Drama, Sci-Fi   
3               Dangal      8.3  Action, Biography, Drama   
4      Rang De Basanti      8.1      Comedy, Crime, Drama   
..                 ...      ...                       ...   
806   Parde Ke Peechey      5.9                    Action   
807            Dhamkee      4.0            Action, Comedy   
808       Chhoo Mantar      6.0                    Comedy   
809  Ladki Sahyadri Ki      5.0            Musical, Drama   
810          Madadgaar      7.2            Drama, Romance   

                                                   act  \
0    Aamir Khan, Madhavan, Mona Singh, Sharman Josh...   
1    Darsheel Safary, Aamir Khan, Tisca Chopra, Vip...   
2    Aamir Khan, Anushka Sharma, Sanjay Dutt, Boman...   
3    Aamir Khan, Sakshi Tanwar, Fatima Sana Shaikh,...   
4    Aamir Khan, Soha Ali Khan, Siddharth, Sharman ...   
..                                                 ...   
806  Vinod Mehra, Yogeeta Bali, Pran Sikand, Bindu ...   
807  Ravi Teja, Anushka Shetty, Krishna, Pradeep Si...   
808  Shyama, Johnny Walker, Anita Guha, Gajanan Jag...   
809  Shalini Abhyankar, Keshavrao Date, Vatsala Des...   
810  Ravindra Kapoor, Indira, Jeevan Dhar, Uma Dutt...   

                                                  Plot  
0    papadum, hairy chest, against the system, comi...  
1    teacher student relationship, dyslexia, agains...  
2    guru, religion, tv reporter, alien on earth, p...  
3    small town, father daughter relationship, male...  
4    delhi india, murder, friend, india, awakening,...  
..                                                 ...  
806                                              crook  
807                                              sorry  
808  rescue, beating, river, village, wedding, flir...  
809                                              sorry  
810                                              sorry  

[811 rows x 5 columns]

In [4]:
movie_df.isna().sum()

Movie Title    0
Ratinng        0
genre          0
act            0
Plot           0
dtype: int64

In [5]:
movie_df.dtypes

Movie Title     object
Ratinng        float64
genre           object
act             object
Plot            object
dtype: object

In [6]:
tfidf = TfidfVectorizer()

In [7]:
vectors = tfidf.fit_transform(movie_df['genre'])

In [8]:
vectors[0].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.83766858,
        0.        , 0.        , 0.54617887, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ]])

In [9]:
vectors[2].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.23854688,
        0.        , 0.        , 0.15553797, 0.        , 0.        ,
        0.67782864, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.67782864, 0.        , 0.        ,
        0.        , 0.        ]])

In [10]:
indexed = pd.Series(index=movie_df['Movie Title'], data=movie_df.index)
indexed

Movie Title
3 Idiots               0
Taare Zameen Par       1
PK                     2
Dangal                 3
Rang De Basanti        4
                    ... 
Parde Ke Peechey     806
Dhamkee              807
Chhoo Mantar         808
Ladki Sahyadri Ki    809
Madadgaar            810
Length: 811, dtype: int64

In [11]:
dis = linear_kernel(vectors[0], vectors)
dis

array([[1.        , 0.17682135, 0.28477478, 0.14539681, 0.68713209,
        0.27882285, 0.44125755, 0.10959635, 1.        , 0.34989062,
        0.73593791, 0.56163239, 0.27882285, 0.56163239, 0.16734622,
        0.10505635, 0.        , 0.28702413, 0.13272403, 0.54617887,
        0.        , 0.20462232, 0.17394914, 0.46705206, 0.13318935,
        0.34989062, 0.56163239, 0.27882285, 0.73593791, 0.48782829,
        0.16384446, 0.44035717, 0.18746835, 0.20462232, 0.56396402,
        0.        , 0.76492377, 0.13272403, 0.16384446, 0.27882285,
        0.53090047, 0.        , 0.        , 0.76492377, 0.10505635,
        0.13272403, 0.13272403, 0.27882285, 0.        , 0.15563719,
        0.44125755, 1.        , 0.73593791, 0.16384446, 0.44125755,
        0.27882285, 0.11589395, 0.13095659, 0.1575185 , 0.25066587,
        0.18746835, 0.20462232, 0.12955874, 1.        , 0.21910022,
        0.17394914, 0.53090047, 0.21910022, 0.18746835, 0.73593791,
        0.20462232, 0.54617887, 0.73593791, 0.  

In [12]:
scores = pd.DataFrame(dis).T
scores.columns = ['Score']
scores

Score
0    1.000000
1    0.176821
2    0.284775
3    0.145397
4    0.687132
..        ...
806  0.000000
807  0.590766
808  0.837669
809  0.189866
810  0.278823

[811 rows x 1 columns]

In [13]:
x = scores.sort_values(by='Score', ascending=False)

In [14]:
x.head(10)

Score
0      1.0
79     1.0
692    1.0
112    1.0
100    1.0
134    1.0
655    1.0
609    1.0
148    1.0
358    1.0

In [20]:
indexed[indexed==261]

Movie Title
Malamaal Weekly    261
dtype: int64